
   
# .goreleaser.yml
# Build customization
builds:
  - main: ./main.go
    binary: release-stats
    ldflags: -s -w -X github.com/TejaBeta/release-stats/cmd.version={{.Version}} -X github.com/TejaBeta/release-stats/cmd.commit={{.Commit}}
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
archives:
  - id: release-stats
    format: tar.gz
    replacements:
      amd64: x86_64
      darwin: Darwin
      linux: Linux
